DEFAULT_CONFIG = {
    "model": "base",
    "language": None,
    "output": None,
    "task": "transcribe",
    "beam_size": 5,
    "compute_type": "default",
    "strict": False,
    "silence_threshold": 2.0,
    "speech_pad": 300,
    "subtitle_segmentation_mode": "auto",
    "subtitle_max_duration": 7.0,
    "force_redetect": False,
    "allow_model_download": False,
    "vad_backend": "pyannote",
}
